- name: Install Python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Include app_prerequisites
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Install Python Dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: Include schema setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: Include SystemD
  ansible.builtin.import_tasks:
    file: systemd_setup.yml

- name: Import Prometheus
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter